### ISSUE TITLE
Ultrawide resolution support

### ISSUE THREAD

**Issue by Hiradur** [Leon280698/CT#3]
Please add support for ultrawide resolutions such as:

21:9 aspect ratio
2560x1080
3440x1440
5120x2160

24:10 aspect ratio
3840x1600

32:9 aspect ratio
3840x1080
5120x1440

32:10 aspect ratio
3840x1200

**Comment by Leon280698** [comment]
This is not really the place for that since the resolution options are not added in code.
However, I'll leave this open since it is somewhat fitting. I'm currently working on a custom launcher that will allow choosing from a dynamically generated list of available resolutions for the current monitor.

**Comment by Hiradur** [comment]
Sorry, I simply followed the link in the mod's readme and thought this was the right place to ask.
Anyway, a dynamically generated list of available resolutions sounds even better.

**Comment by Leon280698** [comment]
Done in https://github.com/Leon280698/CT/commit/be2a0e8a8e588082bfd4191b9583773cdb0adce2

**Comment by Hiradur** [comment]
Thank you for your work.
I tested the version which was uploaded on the 18th of April to moddb (I believe) at a resolution of 3840x1600 and it worked fine on Linux+Wine.
