### ISSUE TITLE
Super high sensitivity.

### ISSUE THREAD

**Issue by emeraldminer299** [Leon280698/CT#6]
After applying the mod, I've had super fast sensitivity. Move my mouse an inch and ZIP, there goes the mouse. I forced Vsync, I forced the refresh rate, but it doesn't seem to fix it.

**Comment by metallicafan212** [comment]
VSync doesn't work on DX8 games on Windows 10 due to the way Microsoft "fixed" some bugs.

Either limit the framerate using something like Rivatuner or use D3D8to9 to convert the game to DX9, which has working VSync.

https://github.com/crosire/d3d8to9

**Comment by Leon280698** [comment]
I don't have this issue for some reason. Could be because of my monitor's adaptive refresh rate which is treated differently by the driver than a fixed one. Forcing a desired refresh rate could be easily done using my custom launcher. The only reason it is not included in the download is that the EditActor command crashes sometimes.
I'll see to it at some point but for now I guess navigating the menus using the keyboard is an acceptable workaround.

**Comment by Leon280698** [comment]
This should now be fixed with the addition of an optional fps limit in version 2.1 of the Graphics Fix https://github.com/Leon280698/CT/releases

**Comment by martixy** [comment]
Mouse sensitivity is still too high.

I play the game at 15,000 DPI and browse the menus at 100, which is the lowest my mouse will go. FPS limited to 240, since my monitor is 165 Hz. Vsync off, Gsync on. The menus become usable at this point, but anything higher than the lowest setting makes the mouse fly.

Not sure if it can be fixed, hence not opening a new issue.

And while not ideal, the FPS limiter makes the menus usable(if annoying), so I'd like to thank you for this mod.
