### ISSUE TITLE
Missing Features from Previous Versions

### ISSUE THREAD

**Issue by Canzah** [Leon280698/CT#8]
Hey,

I noticed that a variety of features from older versions appear to be missing, such as the higher res clone, droid and geonosian textures or ability to look down and see the character's body/legs.
Any reason for this?

**Comment by Leon280698** [comment]
That would require modifying original game files which is something I want to avoid. The goal of the mod is to fix issues with the game but leave it mostly vanilla (except for the Fov slider).
I may add some functionality in the future that allows replacing textures and that kind of stuff at runtime which should be quite easy to do. However, at the moment I’m working on other things first like a new renderer and MP bot support.

**Comment by Canzah** [comment]
Understandable, I assume the reason is that there was some significant changes to the mod under the hood that make it incompatible with the previously available extras?

**Comment by Leon280698** [comment]
Not incompatible just different. At first the mod worked by reimporting the bumpmaps with a working format. Since that already required changing stock packages I threw some hd textures in there because why not.
But now the mod converts the bumpmaps when they are being loaded. Modifying texture packages is no longer necessary now and so I just left that out.
